# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kipukas
email: kipukas.games@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Kipukas Card Binder! Here you will find all of the cards
  that make up Kipukas as well as some important info regarding game play.
  This site will remain free (as in beer) to use always as it is intended
  to enhance the game experiance, not lock you into a pay to play system.
  Our online shop is in active development at kipukas.us where you can find
  more info and make purchases. If desired, you can always email us with
  issues or order requests. Enjoy the site!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kipukas.cards" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  about:

include:
  - _about

exclude:
  - kipukas-server/
  - node_modules/
  - deno.json
  - deno.lock
  - Gemfile
  - Gemfile.lock
  - WORKFLOW.md
  - kipukas_rules_book/
  - scripts/

